<div class="grid_4">
    <div class="boxSpecial">
        <h2>
            <a href="#" id="toggle-navigator">Kliknij aby zobaczyć drzewko...</a>
        </h2>
            <div id="navigator">
                <ul id="browser" class="filetree treeview-famfamfam">
                    <li><span class="folder">User</span>
                        <ul>
                            <li class="closed"><span class="folder">Guides</span>
                                <ul>
                                    <li><span class="file"><a href="#">User Guide</a></span></li>
                                </ul>
                            </li>
                            <li class="closed"><span class="folder">Privacy & Conditions</span>
                                <ul>
                                    <li class="closed"><span class="folder">Privacy</span>
                                        <ul id="folder21">
                                            <li><span class="file"><a href="#">Privacy policies texts (DE/EN)</a></span></li>
                                            <li><span class="file"><a href="#">Privacy general texts (DE/EN)</a></span></li>
                                        </ul>
                                    </li>
                                    <li class="closed"><span class="folder">Terms & Conditions</span>
                                        <ul>
                                            <li><span class="file"><a href="#">Terms texts (DE/EN)</a></span></li>
                                            <li><span class="file"><a href="#">Condition texts (DE/EN)</a></span></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li class="closed"><span class="folder">Revocation Rights</span>
                                <ul>
                                    <li><span class="file"><a href="#">Revocation texts (DE/EN)</a></span></li>
                                </ul>
                            </li>
                            <li><span class="file"><a href="#">General User Text Message</a></span></li>
                        </ul>
                    </li>
                </ul>
            </div>
    </div>
</div>
<div class="grid_12">
    <h2 id="page-crumbs">Templates &raquo; User &raquo; <span class="here">User Name</span></h2>
</div>
<div class="clear"></div>