<div class="grid_16">
    <h2 id="page-heading"><?= $this->title; ?></h2>
</div>
<?= $this->render('templates/navigation.phtml'); ?>   

<div class="grid_7">
    <div class="box">
        <h2>
            <a href="#" id="toggle-articles">Szczegóły</a>
        </h2>
        <div class="block" id="articles">
            <div class="first article">
                <div class="sixteen_column section">
                    <div class="sixteen column">
                        <div class="column_content">
                            <a href="#" class="image">
                                <img src="<?= $this->baseUrl('img/photo_60x60.jpg') ?>" width="60" height="60" alt="photo" />
                            </a>
                            <h3>
                                <a href="#"><?= $this->customer['firstname']." ".$this->customer['lastname'] ?></a>
                            </h3>
                            <h4><?= $this->customer['type']?$this->customer['type']:"NIEZNANY" ?></h4>
                            <?php 
                            $address=$this->customer['province'].", ".$this->customer['city'];
                            $birthday=date("jS F Y",mktime(0,0,0,$this->customer['month'],$this->customer['day'],$this->customer['year']));
                            if(is_null($this->customer['province']) || is_null($this->customer['city']) ){ 
                                $address="Brak informacji o adresie";
                            }
                            if(is_null($this->customer['month']) || is_null($this->customer['day']) || is_null($this->customer['year'])){ 
                                $birthday="Brak informacji o dacie urodzenia";
                            } 
                            ?>
                            <p class="meta"><?= $address ?> — Data urodzenia: <?= $birthday ?></p>
                        </div>
                    </div>
                </div>
                <div class="sixteen_column section">
                    <div class="five column">
                        <div class="column_content">
                            <h5><strong>Dane Kontaktowe</strong></h5>
                            <p><strong>Imię:</strong> <?= $this->customer['firstname'] ?></p>
                            <?php if(!is_null($this->customer['secondname'])){ ?>
                                <p><strong>Drugie imię:</strong> <?= $this->customer['secondname'] ?></p>
                            <?php } ?>
                            <p><strong>Nazwisko:</strong> <?= $this->customer['lastname'] ?></p>
                            <p><strong>Telefon:</strong> <?= $this->customer['phone'] ?></p>
                            <p><strong>Email:</strong> <?= $this->customer['email'] ?></p>
                            <br>
                            <br>
                            <a href="
                               <?=
                                $this->url(
                                            [
                                                'action'=>'edit',
                                                'customers_id'=>$this->customer['customers_id']
                                            ]
                                        );
                               ?>
                               ">Edytuj</a>
                        </div>
                    </div>
                    <div class="eleven column">
                        <div class="column_content">
                            <h5><strong>Pozostałe dane</strong></h5>
                                <div class="sixteen_column section">
                                    <div class="sixteen column">
                                        <div class="column_content">
                                            <p><strong>Profil DB: </strong> <?= $this->customer['wd_profile'] ?></p>
                                            <p><strong>Dni szkoleniowych: </strong> <?= $this->customer['training_days'] ?></p>
                                            <p><strong>NIP: </strong> <?= $this->customer['NIP'] ?></p>
                                        </div>
                                    </div>
                                </div>
                            
                            <form name="tags_form" action="#" method="post">
                                <div class="sixteen_column section">
                                    <div class="eight column">
                                        <div class="column_content">
                                            <label><strong>Przypisane tagi: </strong></label><br>
                                            <?php
                                                if($this->c_tags[0]==''){
                                                    echo "brak przypisanych tagów.";
                                                }else{
                                                    foreach($this->c_tags as $tag){
                                            ?>                                            
                                                    <span class="tag"><span><?= $tag ?>&nbsp;&nbsp;</span></span>
                                            <?php
                                                    }//end foreach
                                                }//end else
                                            ?>
                                        </div>
                                    </div>
                                    <div class="eight column">
                                        <div class="column_content">
                                            <label><strong>Dodaj tagi: </strong></label>
                                            <input type="hidden" id="tags_update_url" name="tags_update_url" value="<?= $this->tags_update_url; ?>" />
                                            <input type="text" name="tags" id="tags_input" value="" />
                                        </div>
                                    </div>
                                </div>
                                <div class="sixteen_column section">
                                  <div class="ten column">
                                      <div class="column_content">
                                      </div>
                                  </div>
                                  <div class="six column">
                                      <div class="column_content">
                                          <a href="#" id="dialog_link" class="ui-state-default ui-corner-some floatRight"><span class="ui-icon ui-icon-disk"></span>Zapisz!</a>
                                      </div>
                                  </div>
                                </div>
                            </form>
                            
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>
<div class="clear"></div>
<div class="grid_16">
    <div class="box">
        <?= $this->partial('customers/table.phtml', array('customers'=>$this->customers)) ?>
    </div>
</div>				
<div class="clear"></div>