<div class="grid_16">
    <h2 id="page-heading">Edycja</h2>
</div>
<?= $this->render('templates/navigation.phtml'); ?>

<div class="grid_7">
    <div class="box">
        <h2>Edycja profilu klienta</h2>
        <div class="block" id="forms">
            <form
                action="<?= $this->form->getAction() ?>"
                method="<?= $this->form->getMethod() ?>"
                >
                <fieldset>
                    <legend>Dane osobowe</legend>
                    <div class="sixteen_column section">
                        <div class="eight column"> 
                            <div class="column_content">
                                <?= $this->form->firstname->renderLabel() ?>
                                <?= $this->form->firstname->renderViewHelper() ?>
                            </div>                            
                        </div>
                        <div class="eight column"> 
                            <div class="column_content">
                                <?= $this->form->lastname->renderLabel() ?>
                                <?= $this->form->lastname->renderViewHelper() ?>
                            </div>                            
                        </div>
                    </div>
                    <div class="sixteen_column section">
                        <div class="four column"> 
                            <div class="column_content">
                                <?= $this->form->phone->renderLabel() ?>
                                <?= $this->form->phone->renderViewHelper() ?>
                            </div>                            
                        </div>
                        <div class="six column"> 
                            <div class="column_content">
                                <?= $this->form->email->renderLabel() ?>
                                <?= $this->form->email->renderViewHelper() ?>
                            </div>                            
                        </div>
                        <div class="six column"> 
                            <div class="column_content">
                                <?= $this->form->type->renderLabel() ?>
                                <?= $this->form->type->renderViewHelper() ?>
                            </div>                            
                        </div>
                    </div>
                    <div class="sixteen_column section">
                        <div class="six column"> 
                            <div class="column_content">
                                <?= $this->form->street->renderLabel() ?>
                                <?= $this->form->street->renderViewHelper() ?>
                            </div>                            
                        </div>
                        <div class="two column"> 
                            <div class="column_content">
                                <?= $this->form->house_no->renderLabel() ?>
                                <?= $this->form->house_no->renderViewHelper() ?>
                            </div>                            
                        </div>
                        <div class="two column"> 
                            <div class="column_content">
                                <?= $this->form->flat_no->renderLabel() ?>
                                <?= $this->form->flat_no->renderViewHelper() ?>
                            </div>                            
                        </div>
                        <div class="six column"> 
                            <div class="column_content">
                                <?= $this->form->city->renderLabel() ?>
                                <?= $this->form->city->renderViewHelper() ?>
                            </div>                            
                        </div>
                    </div>
                    <div class="sixteen_column section">
                        <div class="eight column"> 
                            <div class="column_content">
                            </div>                            
                        </div>
                        <div class="eight column"> 
                            <div class="column_content">
                                <?= $this->form->submit->renderViewHelper() ?>
                            </div>                            
                        </div>
                    </div>
                </fieldset>
                
            </form>
        </div>
    </div>    
</div>