<div class="grid_16">
    <h2 id="page-heading">Pulpit</h2>
</div>
<?= $this->render('templates/navigation.phtml'); ?>   

<div class="grid_6">
    <h1>Witaj w Panelu Administratora Treehouse Origin!</h1>
    <h3>Z czasem będzie stawał się on coraz bogatszy. Na dzień dzisiejszy dostępna funkcjonalność to:</h3>
    <ul>
        <li>Wyświetlenie listy szkoleń</li>
        <li>Wyświetlenie listy uczestników danego szkolenia</li>
        <li>Podstawowe operacje - edycja, usuwanie, dodwanie rekordów</li>
        <li>export listy uczestników do <strong>pdf/xls</strong></li>
    </ul>
</div>