<!doctype html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	
	<?= $this->headTitle($this->title); ?>
	<meta name="description" content="">
	<meta name="author" content="">
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<link rel="shortcut icon" href="/favicon.ico">
	<link rel="apple-touch-icon" href="/apple-touch-icon.png">
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/style.css?v=2"); ?>">
        
	<!-- fluid 960 -->
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl("css/text.css"); ?>" media="screen" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl("css/layout.css"); ?>" media="screen" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl("css/grid.css"); ?>" media="screen" />
	<!-- superfish menu -->
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl("css/superfish.css"); ?>" media="screen" />
	<!-- tags css -->
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery.tagsinput.css"); ?>">
	<!-- treeview css -->
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery.treeview.css"); ?>">
	<!-- dataTable css -->
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/demo_table_jui.css"); ?>">


	<!-- fluid GS -->
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl("css/fluid.gs.css"); ?>" media="screen" />
	<!--[if lt IE 8 ]>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl("css/fluid.gs.lt_ie8.css"); ?>" media="screen" />
	<![endif]-->

	<!-- //jqueryUI css -->
	<link type="text/css" href="<?php echo $this->baseUrl("css/custom-theme/jquery-ui-1.8.13.custom.css"); ?>" rel="stylesheet" />
	
	<!-- //jquery -->
	<!-- <script src="//ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script> -->
	<script src="<?php echo $this->baseUrl("js/libs/jquery-1.5.1.min.js"); ?>"></script>
	<script>!window.jQuery && document.write(unescape('%3Cscript src="js/libs/jquery-1.5.1.min.js"%3E%3C/script%3E'))</script>
	<!-- //jqueryUI -->
	<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery-ui-1.8.13.custom.min.js"); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery-fluid16.js"); ?>"></script>
	<script src="<?php echo $this->baseUrl("js/plugins.js"); ?>"></script>
	<script src="<?php echo $this->baseUrl("js/script.js"); ?>"></script>
	
	<!-- //xoxco tags plugin https://github.com/xoxco/jQuery-Tags-Input -->
	<script src="<?php echo $this->baseUrl("js/jquery.tagsinput.min.js"); ?>"></script>
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery.tagsinput.css"); ?>">
	
	<!--[if lt IE 7 ]>
	<script src="<?php echo $this->baseUrl("js/libs/dd_belatedpng.js"); ?>"></script>
	<script> DD_belatedPNG.fix('img, .png_bg');</script>
	<![endif]-->
	<!-- modernizr -->
	<script src="<?php echo $this->baseUrl("js/libs/modernizr-1.7.min.js"); ?>"></script>
	
	<!-- superfish menu and needed js for menu -->
	<script src="<?php echo $this->baseUrl("js/superfish.js"); ?>"></script>
	<script src="<?php echo $this->baseUrl("js/supersubs.js"); ?>"></script>
	<script src="<?php echo $this->baseUrl("js/hoverIntent.js"); ?>"></script>

	<!-- treeview -->
	<script src="<?php echo $this->baseUrl("js/jquery.treeview.js"); ?>"></script>
	
	<!-- dataTable -->
	<script src="<?php echo $this->baseUrl("js/jquery.dataTables.min.js"); ?>"></script>
        
        <!-- jQuery ready function -->
	<script src="<?php echo $this->baseUrl("js/jquery.ready.js"); ?>"></script>
</head>
<body>
    <div class="container_16">
        <header>
            <?= $this->render('header.phtml') ?>
        </header>
        
        <div class="grid_16">
            <?= $this->render('menu.phtml') ?>
        </div>
        
        <div class="clear"></div>
        
        
        <div id="main" role="main">
            <?= $this->layout()->content; ?>
        </div>

        <footer>
            <?= $this->render('footer.phtml') ?>
        </footer>
    </div>
</body>
</html>