<ul class="sf-menu" id="navigationTop">
    <li>
        <a href="<?php echo $this->url(array(),"index"); ?>">Pulpit</a>
    </li>
     <!-- class="selected" - zaznaczona aktualna zakładka menu -->
    <!--<li>
        <a href="<?php echo $this->url(array(),"events"); ?>">Szkolenia</a>
    </li>-->
    <li>
        <a href="<?php echo $this->url(array(),"customers"); ?>">Klienci</a>
    </li>
</ul>