<ul class="sf-menu sf-js-enabled sf-shadow" id="navigationTop">
    <li>
        <a href="<?php echo $this->url(array(),"index"); ?>">Pulpit</a>
    </li>
     <!-- class="selected" - zaznaczona aktualna zakładka menu -->
    <!--<li>
        <a href="<?php echo $this->url(array(),"events"); ?>">Szkolenia</a>
    </li>-->
    <li class="selected">
        <a href="<?php echo $this->url(array(),"customers"); ?>" >Klienci</a>
        <ul>
            <li><a href="<?php echo $this->url(array("controller"=>"Customers","action"=>"createform"),"default"); ?>">Dodaj nowego</a></li>
        </ul>
    </li>
</ul>