<ul class="sf-menu sf-js-enabled sf-shadow" id="navigationTop">
    <li class="<?= (strtolower($this->controllerName)=='index'?'selected':'') ?>">
        <a href="<?= $this->url(array(),"index"); ?>">Pulpit</a>
    </li>
     <!-- class="selected" - zaznaczona aktualna zakładka menu -->
    <!--<li>
        <a href="<?= $this->url(array(),"events"); ?>">Szkolenia</a>
    </li>-->
    <li class="sf-link <?= (strtolower($this->controllerName)=='customers'?'selected':'') ?>">
        <a class="sf-with-ul" href="<?= $this->url(array(),"customers"); ?>" >Klienci</a>
        <span class="sf-sub-indicator"> »</span>
        <ul>
            <li><a class="sf-with-ul" href="<?= $this->url(array(),"customers"); ?>" >Wyświetl wszystkich</a></li>
            <li><a href="<?= $this->url(array("controller"=>"customers","action"=>"createform"),"default"); ?>">Dodaj nowego</a></li>
        </ul>
    </li>
</ul>